install f5-cloud-libs-* as a peer

diff --git a/gitHooks/pre-commit b/gitHooks/pre-commit
--- a/gitHooks/pre-commit
+++ b/gitHooks/pre-commit
@@ -2,7 +2,16 @@
 #
 BRANCH=`git rev-parse --abbrev-ref HEAD`
 
-if ! npm test; then
+echo "Running lint"
+if ! npm run lint; then
+    echo
+    echo "Rejecting commit: Linting failed."
+    echo
+    exit 1
+fi
+
+echo "Running unit tests"
+if ! npm run test -- --reporter minimal; then
     echo
     echo "Rejecting commit: Unit tests failed."
     echo
@@ -10,6 +19,7 @@ if ! npm test; then
 fi
 
 if [[ "$BRANCH" != master && "$BRANCH" != release-* && "$BRANCH" != hf-* ]]; then
+    echo "Packaging"
     npm run package
     git add dist
 fi
